var namespacetesting =
[
    [ "gtest_printers_test", "namespacetesting_1_1gtest__printers__test.html", "namespacetesting_1_1gtest__printers__test" ],
    [ "internal", "namespacetesting_1_1internal.html", "namespacetesting_1_1internal" ],
    [ "internal2", "namespacetesting_1_1internal2.html", "namespacetesting_1_1internal2" ],
    [ "AssertionResult", "classtesting_1_1_assertion_result.html", "classtesting_1_1_assertion_result" ],
    [ "CodeLocationForTESTF", "classtesting_1_1_code_location_for_t_e_s_t_f.html", null ],
    [ "CodeLocationForTESTP", "classtesting_1_1_code_location_for_t_e_s_t_p.html", null ],
    [ "CodeLocationForTYPEDTEST", "classtesting_1_1_code_location_for_t_y_p_e_d_t_e_s_t.html", null ],
    [ "CodeLocationForTYPEDTESTP", "classtesting_1_1_code_location_for_t_y_p_e_d_t_e_s_t_p.html", null ],
    [ "CurrentTestInfoTest", "classtesting_1_1_current_test_info_test.html", null ],
    [ "EmptyTestEventListener", "classtesting_1_1_empty_test_event_listener.html", "classtesting_1_1_empty_test_event_listener" ],
    [ "Environment", "classtesting_1_1_environment.html", "classtesting_1_1_environment" ],
    [ "Flags", "structtesting_1_1_flags.html", "structtesting_1_1_flags" ],
    [ "InitGoogleTestTest", "classtesting_1_1_init_google_test_test.html", "classtesting_1_1_init_google_test_test" ],
    [ "Message", "classtesting_1_1_message.html", "classtesting_1_1_message" ],
    [ "ScopedFakeTestPartResultReporter", "classtesting_1_1_scoped_fake_test_part_result_reporter.html", "classtesting_1_1_scoped_fake_test_part_result_reporter" ],
    [ "SetUpTestCaseTest", "classtesting_1_1_set_up_test_case_test.html", "classtesting_1_1_set_up_test_case_test" ],
    [ "Test", "classtesting_1_1_test.html", "classtesting_1_1_test" ],
    [ "TestCase", "classtesting_1_1_test_case.html", "classtesting_1_1_test_case" ],
    [ "TestEventListener", "classtesting_1_1_test_event_listener.html", "classtesting_1_1_test_event_listener" ],
    [ "TestEventListeners", "classtesting_1_1_test_event_listeners.html", "classtesting_1_1_test_event_listeners" ],
    [ "TestInfo", "classtesting_1_1_test_info.html", "classtesting_1_1_test_info" ],
    [ "TestInfoTest", "classtesting_1_1_test_info_test.html", null ],
    [ "TestPartResult", "classtesting_1_1_test_part_result.html", "classtesting_1_1_test_part_result" ],
    [ "TestPartResultArray", "classtesting_1_1_test_part_result_array.html", "classtesting_1_1_test_part_result_array" ],
    [ "TestPartResultReporterInterface", "classtesting_1_1_test_part_result_reporter_interface.html", "classtesting_1_1_test_part_result_reporter_interface" ],
    [ "TestProperty", "classtesting_1_1_test_property.html", "classtesting_1_1_test_property" ],
    [ "TestResult", "classtesting_1_1_test_result.html", "classtesting_1_1_test_result" ],
    [ "UnitTest", "classtesting_1_1_unit_test.html", "classtesting_1_1_unit_test" ]
];