var namespaces_dup =
[
    [ "bar", "namespacebar.html", null ],
    [ "common", "namespacecommon.html", null ],
    [ "foo", "namespacefoo.html", null ],
    [ "fuse_gtest_files", "namespacefuse__gtest__files.html", null ],
    [ "gen_gtest_pred_impl", "namespacegen__gtest__pred__impl.html", null ],
    [ "gtest_break_on_failure_unittest", "namespacegtest__break__on__failure__unittest.html", null ],
    [ "gtest_catch_exceptions_test", "namespacegtest__catch__exceptions__test.html", null ],
    [ "gtest_color_test", "namespacegtest__color__test.html", null ],
    [ "gtest_env_var_test", "namespacegtest__env__var__test.html", null ],
    [ "gtest_filter_unittest", "namespacegtest__filter__unittest.html", null ],
    [ "gtest_help_test", "namespacegtest__help__test.html", null ],
    [ "gtest_list_tests_unittest", "namespacegtest__list__tests__unittest.html", null ],
    [ "gtest_output_test", "namespacegtest__output__test.html", null ],
    [ "gtest_shuffle_test", "namespacegtest__shuffle__test.html", null ],
    [ "gtest_test_utils", "namespacegtest__test__utils.html", null ],
    [ "gtest_throw_on_failure_test", "namespacegtest__throw__on__failure__test.html", null ],
    [ "gtest_uninitialized_test", "namespacegtest__uninitialized__test.html", null ],
    [ "gtest_xml_outfiles_test", "namespacegtest__xml__outfiles__test.html", null ],
    [ "gtest_xml_output_unittest", "namespacegtest__xml__output__unittest.html", null ],
    [ "gtest_xml_test_utils", "namespacegtest__xml__test__utils.html", null ],
    [ "my_namespace", "namespacemy__namespace.html", "namespacemy__namespace" ],
    [ "namespace1", "namespacenamespace1.html", null ],
    [ "namespace2", "namespacenamespace2.html", null ],
    [ "proto2", "namespaceproto2.html", null ],
    [ "pump", "namespacepump.html", null ],
    [ "release_docs", "namespacerelease__docs.html", null ],
    [ "std", "namespacestd.html", "namespacestd" ],
    [ "testing", "namespacetesting.html", "namespacetesting" ],
    [ "testing_internal", "namespacetesting__internal.html", null ],
    [ "upload", "namespaceupload.html", null ],
    [ "upload_gtest", "namespaceupload__gtest.html", null ],
    [ "versiongenerate", "namespaceversiongenerate.html", null ]
];